In [1]:
import numba
import numpy as np

In [5]:
import atm_c14_data

In [6]:
c_a = atm_c14_data.K

In [7]:
c_min = atm_c14_data.c14_data['d14C'].min()
c_max = atm_c14_data.c14_data['d14C'].max()
c_min, c_max

(-0.024899999999999999, 0.8357)

In [26]:
c

array([-0.0249    ,  0.07072222,  0.16634444,  0.26196667,  0.35758889,
        0.45321111,  0.54883333,  0.64445556,  0.74007778,  0.8357    ])

In [ ]:
i = (cc - 0.5 * dc) // dc + 1

In [41]:
c = np.linspace(c_min, c_max, 10, endpoint=True)

dc = c[2] - c[1]

cc = 0.85
i = 
print i
c[int(i)]

9.0


0.8357

In [90]:
c.astype

array([-0.0249    ,  0.07072222,  0.16634444,  0.26196667,  0.35758889,
        0.45321111,  0.54883333,  0.64445556,  0.74007778,  0.8357    ])

In [188]:
len(c_bins)

100

In [189]:
c_bins = np.linspace(c_min, c_max, bins, endpoint=True)

def bin_index(c):
    dc = c_bins[1] - c_bins[0]
    return (np.floor_divide(c + c_min, dc)).astype(int)

c = c_a(1950)

dc = c_bins[1] - c_bins[0]
c = c_max
np.floor_divide((c /(c_max - c_min)) * (c - c_min), dc)

96.0

In [166]:
def c_profile(D_birth, D_coll, r, t_steps = 100, bins = 100, n0 = None):
    
    c_bins = np.linspace(c_min, c_max, bins, endpoint=True)
    
    def bin_index(c):
        dc = c_bins[1] - c_bins[0]
        return (np.floor_divide(c, dc)).astype(int)
    
    if n0 is None:
        n0 = np.zeros_like(c_bins)
        n0[bin_index(c_a(D_birth))] = 1
    n0 /= np.sum(n0)
    
    
    times = np.linspace(D_birth, D_coll, t_steps, endpoint=True)
    dt = times[1] - times[0]
     
    n = n0    
    for t in times:
        target = bin_index(0.5 * (c_a(t) + c_bins))
        target = np.outer(np.ones_like(n0), target)
        
        n_arg = np.outer(np.arange(len(n0)), np.ones_like(n0))
        
        D = target == n_arg
        
        n = n - r * n + r * np.sum(D * n, axis = 1)
        
    print bin_index(c_a(1950))
    print c_bins
    return np.average(c_bins, weights=n)
    
print c_a(1950)
c_profile(1950, 2000, r= 0.0, bins = 100, t_steps=100)

-0.0247
-3
[-0.0249     -0.01620707 -0.00751414  0.00117879  0.00987172  0.01856465
  0.02725758  0.03595051  0.04464343  0.05333636  0.06202929  0.07072222
  0.07941515  0.08810808  0.09680101  0.10549394  0.11418687  0.1228798
  0.13157273  0.14026566  0.14895859  0.15765152  0.16634444  0.17503737
  0.1837303   0.19242323  0.20111616  0.20980909  0.21850202  0.22719495
  0.23588788  0.24458081  0.25327374  0.26196667  0.2706596   0.27935253
  0.28804545  0.29673838  0.30543131  0.31412424  0.32281717  0.3315101
  0.34020303  0.34889596  0.35758889  0.36628182  0.37497475  0.38366768
  0.39236061  0.40105354  0.40974646  0.41843939  0.42713232  0.43582525
  0.44451818  0.45321111  0.46190404  0.47059697  0.4792899   0.48798283
  0.49667576  0.50536869  0.51406162  0.52275455  0.53144747  0.5401404
  0.54883333  0.55752626  0.56621919  0.57491212  0.58360505  0.59229798
  0.60099091  0.60968384  0.61837677  0.6270697   0.63576263  0.64445556
  0.65314848  0.66184141  0.67053434  0.679

0.81831414141414149

In [137]:
D * np.array([1,2,3])

array([[1, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])